const carModelsByManufacturer: Record<string, string[]> = {
  Ford: [
    'Mustang',
    'Fusion',
    'Focus',
    'Escape',
    'Explorer',
    'F-150',
    'Edge',
    'Ranger',
    'Expedition',
    'Bronco',
    'Maverick',
  ],
  Nissan: [
    'Altima',
    'Maxima',
    'Sentra',
    'Versa',
    'Rogue',
    'Murano',
    'Pathfinder',
    'Frontier',
    'Titan',
    'Armada',
    'Leaf',
  ],
  Toyota: [
    'Camry',
    'Corolla',
    'Rav4',
    'Highlander',
    'Tacoma',
    '4Runner',
    'Sienna',
    'Prius',
    'Tundra',
    'Avalon',
    'Supra',
  ],
  Honda: [
    'Accord',
    'Civic',
    'CR-V',
    'Pilot',
    'Odyssey',
    'Fit',
    'Ridgeline',
    'HR-V',
    'Insight',
    'Passport',
    'Clarity',
  ],
  Chevrolet: [
    'Silverado',
    'Equinox',
    'Malibu',
    'Traverse',
    'Tahoe',
    'Camaro',
    'Colorado',
    'Suburban',
    'Blazer',
    'Trailblazer',
    'Spark',
  ],
  Volkswagen: [
    'Jetta',
    'Passat',
    'Tiguan',
    'Atlas',
    'Golf',
    'Arteon',
    'ID.4',
    'Taos',
    'Atlas',
    'Golf GTI',
    'Touareg',
  ],
  BMW: [
    '3 Series',
    '5 Series',
    'X3',
    'X5',
    '7 Series',
    'X1',
    'X7',
    '4 Series',
    'X6',
    '2 Series',
    'X4',
  ],
  Mercedes: [
    'C-Class',
    'E-Class',
    'S-Class',
    'GLC',
    'GLE',
    'A-Class',
    'CLA',
    'GLA',
    'G-Class',
    'GLB',
    'GLS',
  ],
  Audi: ['A4', 'A6', 'Q5', 'Q7', 'A3', 'Q3', 'A5', 'Q8', 'A7', 'RS6', 'E-Tron'],
  Hyundai: [
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Kona',
    'Palisade',
    'Accent',
    'Veloster',
    'Venue',
    'Nexo',
    'Ioniq',
  ],
  Kia: [
    'Forte',
    'Optima',
    'Sportage',
    'Sorento',
    'Telluride',
    'Soul',
    'Rio',
    'Stinger',
    'Cadenza',
    'K5',
    'EV6',
  ],
  Subaru: [
    'Outback',
    'Forester',
    'Crosstrek',
    'Legacy',
    'Impreza',
    'Ascent',
    'WRX',
    'BRZ',
    'Crosstrek Hybrid',
    'WRX STI',
    'Baja',
  ],
  Mazda: [
    'Mazda3',
    'Mazda6',
    'CX-5',
    'CX-9',
    'MX-5 Miata',
    'CX-30',
    'CX-3',
    'Mazda5',
    'Mazda2',
    'RX-8',
    'MX-30',
  ],
  Lexus: ['RX', 'ES', 'NX', 'GX', 'UX', 'IS', 'LS', 'RC', 'LC', 'LX', 'LFA'],
};

export default carModelsByManufacturer;
